### ISSUE TITLE
[BUG] - Wrong country codes

### ISSUE THREAD

**Issue by rage4** [vultr/vultr-docs#1]
**Describe the bug**
The https://github.com/vultr/vultr-docs/tree/main/faq/as20473-bgp-customer-guide contains incorrect ISO country codes for Spain, the United Kingdom and the Netherlands. The correct ISO code is 
- Spain - ES
- United Kingdom - GB 
- Netherlands - NL

**Comment by ghost** [comment]
Corrected in https://github.com/tomasconstant/add-bombay/pull/1

**Comment by ghost** [comment]
Updated article.
