### ISSUE TITLE
[BUG] - Selective Advertisements to Public Peers not Working

### ISSUE THREAD

**Issue by tkoch96** [vultr/vultr-docs#18]
Hello,

I am trying to selectively advertise a prefix to one public peer (AS9370) at Tokyo. However, according to the peer's looking glass (http://as9370.bgp4.jp/), the advertisement is not propagating.

The communities I am attaching are 20473:6000 and 20473:6099:9370

I tried only attaching the community 20473:6099:9370, but then the prefix propagated to all peers/providers at Tokyo.

According to the README, these communities should be the ones to attach, unless I'm misunderstanding something. I'd appreciate any help with this issue that you can provide.

**Comment by tomasconstant** [comment]
Sorry for the late answer. If you are a Vultr customer is better to open a ticket. In any case, it should be working now. If it's not working, please open a ticket.
